image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  CONTAINER_LOCAL_IMAGE: skia
  CONTAINER_REGISTRY: registry.ebu.io
  CONTAINER_IMAGE_NAME: vidtext/skia

build:
  stage: build
  script:
    - apk add --no-cache git
    - export IMAGE_TAG=`git describe --always --tags --first-parent`
    - echo $IMAGE_TAG > VERSION
    - docker build -t $CONTAINER_LOCAL_IMAGE .
    - docker login -u dind-runner -p $REGISTRY_PASSWORD $CONTAINER_REGISTRY
    - docker tag $CONTAINER_LOCAL_IMAGE $CONTAINER_REGISTRY/$CONTAINER_IMAGE_NAME:$IMAGE_TAG
    - docker push $CONTAINER_REGISTRY/$CONTAINER_IMAGE_NAME:$IMAGE_TAG
    - echo $CONTAINER_REGISTRY/$CONTAINER_IMAGE_NAME:$IMAGE_TAG
  tags:
    - dind
